name: Deploy website on push

# controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  web-deploy:
    name: deploy

    # Type of runner the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Get latest code

      # Checks out your repository under $GITIHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    - name: synch files
      uses: modabpaints/FTP-Deploy-Action@4.1.0
      with: 
        server: ftp.modabpaints.com
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: /
