name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: debug
      run: |
        echo "Debugging information"
        echo "FTP_SERVER: ${{ secrets.SERVER }}"
        echo "FTP_USERNAME: ${{ secrets.USERNAME }}"
        echo "FTP_PASSWORD: ${{ secrets.PASSWORD }}"
        echo "Current directory: $(pwd)"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install  # Change this if your project uses a different package manager

    - name: Deploy to cPanel
      env:
        FTP_SERVER: ${{ secrets.SERVER }}
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        chmod +x deploy.sh
        ./deploy.sh
